package PokerRoom

class GGTableFilePaths : ITableFilePaths {


    override val Btn1Path = "c:/resources/buttons/btn1.png"
    override val Btn2Path = "c:/resources/buttons/btn2.png"
    override val Btn3Path = "c:/resources/buttons/btn3.png"
    override val Btn4Path = "c:/resources/buttons/btn4.png"
    override val Btn5Path = "c:/resources/buttons/btn5.png"
    override val Btn6Path = "c:/resources/buttons/btn6.png"

    override val h2Hero = "c:/resources/hero/h2.png"
    override val h3Hero = "c:/resources/hero/h3.png"
    override val h4Hero = "c:/resources/hero/h4.png"
    override val h5Hero = "c:/resources/hero/h5.png"
    override val h6Hero = "c:/resources/hero/h6.png"
    override val h7Hero = "c:/resources/hero/h7.png"
    override val h8Hero = "c:/resources/hero/h8.png"
    override val h9Hero = "c:/resources/hero/h9.png"
    override val htHero = "c:/resources/hero/ht.png"
    override val hjHero = "c:/resources/hero/hj.png"
    override val hqHero = "c:/resources/hero/hq.png"
    override val hkHero = "c:/resources/hero/hk.png"
    override val haHero = "c:/resources/hero/ha.png"

    override val d2Hero = "c:/resources/hero/d2.png"
    override val d3Hero = "c:/resources/hero/d3.png"
    override val d4Hero = "c:/resources/hero/d4.png"
    override val d5Hero = "c:/resources/hero/d5.png"
    override val d6Hero = "c:/resources/hero/d6.png"
    override val d7Hero = "c:/resources/hero/d7.png"
    override val d8Hero = "c:/resources/hero/d8.png"
    override val d9Hero = "c:/resources/hero/d9.png"
    override val dtHero = "c:/resources/hero/dt.png"
    override val djHero = "c:/resources/hero/dj.png"
    override val dqHero = "c:/resources/hero/dq.png"
    override val dkHero = "c:/resources/hero/dk.png"
    override val daHero = "c:/resources/hero/da.png"

    override val c2Hero = "c:/resources/hero/c2.png"
    override val c3Hero = "c:/resources/hero/c3.png"
    override val c4Hero = "c:/resources/hero/c4.png"
    override val c5Hero = "c:/resources/hero/c5.png"
    override val c6Hero = "c:/resources/hero/c6.png"
    override val c7Hero = "c:/resources/hero/c7.png"
    override val c8Hero = "c:/resources/hero/c8.png"
    override val c9Hero = "c:/resources/hero/c9.png"
    override val ctHero = "c:/resources/hero/ct.png"
    override val cjHero = "c:/resources/hero/cj.png"
    override val cqHero = "c:/resources/hero/cq.png"
    override val ckHero = "c:/resources/hero/ck.png"
    override val caHero = "c:/resources/hero/ca.png"

    override val s2Hero = "c:/resources/hero/s2.png"
    override val s3Hero = "c:/resources/hero/s3.png"
    override val s4Hero = "c:/resources/hero/s4.png"
    override val s5Hero = "c:/resources/hero/s5.png"
    override val s6Hero = "c:/resources/hero/s6.png"
    override val s7Hero = "c:/resources/hero/s7.png"
    override val s8Hero = "c:/resources/hero/s8.png"
    override val s9Hero = "c:/resources/hero/s9.png"
    override val stHero = "c:/resources/hero/st.png"
    override val sjHero = "c:/resources/hero/sj.png"
    override val sqHero = "c:/resources/hero/sq.png"
    override val skHero = "c:/resources/hero/sk.png"
    override val saHero = "c:/resources/hero/sa.png"


}