package PokerRoom

class GGTableFilePaths : ITableFilePaths {


    override val Btn1Path = "c:/resources/buttons/btn1.png"
    override val Btn2Path = "c:/resources/buttons/btn2.png"
    override val Btn3Path = "c:/resources/buttons/btn3.png"
    override val Btn4Path = "c:/resources/buttons/btn4.png"
    override val Btn5Path = "c:/resources/buttons/btn5.png"
    override val Btn6Path = "c:/resources/buttons/btn6.png"

    override val h2 = "c:/resources/hero/h2.png"
    override val h3 = "c:/resources/hero/h3.png"
    override val h4 = "c:/resources/hero/h4.png"
    override val h5 = "c:/resources/hero/h5.png"
    override val h6 = "c:/resources/hero/h6.png"
    override val h7 = "c:/resources/hero/h7.png"
    override val h8 = "c:/resources/hero/h8.png"
    override val h9 = "c:/resources/hero/h9.png"
    override val ht = "c:/resources/hero/ht.png"
    override val hj = "c:/resources/hero/hj.png"
    override val hq = "c:/resources/hero/hq.png"
    override val hk = "c:/resources/hero/hk.png"
    override val ha = "c:/resources/hero/ha.png"

    override val d2 = "c:/resources/hero/d2.png"
    override val d3 = "c:/resources/hero/d3.png"
    override val d4 = "c:/resources/hero/d4.png"
    override val d5 = "c:/resources/hero/d5.png"
    override val d6 = "c:/resources/hero/d6.png"
    override val d7 = "c:/resources/hero/d7.png"
    override val d8 = "c:/resources/hero/d8.png"
    override val d9 = "c:/resources/hero/d9.png"
    override val dt = "c:/resources/hero/dt.png"
    override val dj = "c:/resources/hero/dj.png"
    override val dq = "c:/resources/hero/dq.png"
    override val dk = "c:/resources/hero/dk.png"
    override val da = "c:/resources/hero/da.png"

    override val c2 = "c:/resources/hero/c2.png"
    override val c3 = "c:/resources/hero/c3.png"
    override val c4 = "c:/resources/hero/c4.png"
    override val c5 = "c:/resources/hero/c5.png"
    override val c6 = "c:/resources/hero/c6.png"
    override val c7 = "c:/resources/hero/c7.png"
    override val c8 = "c:/resources/hero/c8.png"
    override val c9 = "c:/resources/hero/c9.png"
    override val ct = "c:/resources/hero/ct.png"
    override val cj = "c:/resources/hero/cj.png"
    override val cq = "c:/resources/hero/cq.png"
    override val ck = "c:/resources/hero/ck.png"
    override val ca = "c:/resources/hero/ca.png"

    override val s2 = "c:/resources/hero/s2.png"
    override val s3 = "c:/resources/hero/s3.png"
    override val s4 = "c:/resources/hero/s4.png"
    override val s5 = "c:/resources/hero/s5.png"
    override val s6 = "c:/resources/hero/s6.png"
    override val s7 = "c:/resources/hero/s7.png"
    override val s8 = "c:/resources/hero/s8.png"
    override val s9 = "c:/resources/hero/s9.png"
    override val st = "c:/resources/hero/st.png"
    override val sj = "c:/resources/hero/sj.png"
    override val sq = "c:/resources/hero/sq.png"
    override val sk = "c:/resources/hero/sk.png"
    override val sa = "c:/resources/hero/sa.png"


}