package PokerRoom

class GGTableFilePaths : ITableFilePaths {


    override val Btn1Path = "c:/resources/buttons/btn1.png"
    override val Btn2Path = "c:/resources/buttons/btn2.png"
    override val Btn3Path = "c:/resources/buttons/btn3.png"
    override val Btn4Path = "c:/resources/buttons/btn4.png"
    override val Btn5Path = "c:/resources/buttons/btn5.png"
    override val Btn6Path = "c:/resources/buttons/btn6.png"

    override val h2 = "c:/resources/buttons/h2.png"
    override val h3 = "c:/resources/buttons/h3.png"
    override val h4 = "c:/resources/buttons/h4.png"
    override val h5 = "c:/resources/buttons/h5.png"
    override val h6 = "c:/resources/buttons/h6.png"
    override val h7 = "c:/resources/buttons/h7.png"
    override val h8 = "c:/resources/buttons/h8.png"
    override val h9 = "c:/resources/buttons/h9.png"
    override val ht = "c:/resources/buttons/ht.png"
    override val hj = "c:/resources/buttons/hj.png"
    override val hq = "c:/resources/buttons/hq.png"
    override val hk = "c:/resources/buttons/hk.png"
    override val ha = "c:/resources/buttons/ha.png"

    override val d2 = "c:/resources/buttons/d2.png"
    override val d3 = "c:/resources/buttons/d3.png"
    override val d4 = "c:/resources/buttons/d4.png"
    override val d5 = "c:/resources/buttons/d5.png"
    override val d6 = "c:/resources/buttons/d6.png"
    override val d7 = "c:/resources/buttons/d7.png"
    override val d8 = "c:/resources/buttons/d8.png"
    override val d9 = "c:/resources/buttons/d9.png"
    override val dt = "c:/resources/buttons/dt.png"
    override val dj = "c:/resources/buttons/dj.png"
    override val dq = "c:/resources/buttons/dq.png"
    override val dk = "c:/resources/buttons/dk.png"
    override val da = "c:/resources/buttons/da.png"

    override val c2 = "c:/resources/buttons/c2.png"
    override val c3 = "c:/resources/buttons/c3.png"
    override val c4 = "c:/resources/buttons/c4.png"
    override val c5 = "c:/resources/buttons/c5.png"
    override val c6 = "c:/resources/buttons/c6.png"
    override val c7 = "c:/resources/buttons/c7.png"
    override val c8 = "c:/resources/buttons/c8.png"
    override val c9 = "c:/resources/buttons/c9.png"
    override val ct = "c:/resources/buttons/ct.png"
    override val cj = "c:/resources/buttons/cj.png"
    override val cq = "c:/resources/buttons/cq.png"
    override val ck = "c:/resources/buttons/ck.png"
    override val ca = "c:/resources/buttons/ca.png"

    override val s2 = "c:/resources/buttons/s2.png"
    override val s3 = "c:/resources/buttons/s3.png"
    override val s4 = "c:/resources/buttons/s4.png"
    override val s5 = "c:/resources/buttons/s5.png"
    override val s6 = "c:/resources/buttons/s6.png"
    override val s7 = "c:/resources/buttons/s7.png"
    override val s8 = "c:/resources/buttons/s8.png"
    override val s9 = "c:/resources/buttons/s9.png"
    override val st = "c:/resources/buttons/st.png"
    override val sj = "c:/resources/buttons/sj.png"
    override val sq = "c:/resources/buttons/sq.png"
    override val sk = "c:/resources/buttons/sk.png"
    override val sa = "c:/resources/buttons/sa.png"


}